version: "3.9"
services:
  redis:
    image: redis:7-alpine
    container_name: dispo_redis
    ports: ["6379:6379"]
    restart: unless-stopped
  app:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "npm install && node server.js"
    environment:
      - PORT=3000
      - CORS_ORIGIN=*
      - REDIS_URL=redis://redis:6379
      - CACHE_TTL_SECONDS=180
      - POLL_MINUTES=2
      - APPLE_COUNTRY=fr
      - DEV_TOKEN=changeme
    ports: ["3000:3000"]
    depends_on:
      - redis
